# Generated by Django 4.2.15 on 2024-09-28 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="creator",
            field=models.CharField(default="2024-01-01 00:00:00", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projects",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
