# Generated by Django 4.2.15 on 2024-09-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projects_created_at_projects_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="creator",
        ),
    ]
