# Generated by Django 4.2.15 on 2024-09-28 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_alter_roles_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="roles",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roles",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
