# Generated by Django 4.2.15 on 2024-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("img_url", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
