# Generated by Django 4.2.15 on 2024-09-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(default="member", max_length=20),
        ),
        migrations.AlterField(
            model_name="users",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="img_url",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
