# Generated by Django 4.2.15 on 2024-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_users_role_alter_users_address_alter_users_img_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
