# Generated by Django 4.2.15 on 2024-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
