# Generated by Django 4.2.15 on 2024-09-08 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
